environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "14"
    - nodejs_version: "16"

cache:
  - node_modules   

platform:
  - x86
  - x64

branches:
  only:
  - master

skip_tags: true

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

before_build:
- npm run eslint

test_script:
  - node --version
  - npm --version
  - npm test

build: off
